apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "refinery.fullname" . }}-rules
  labels:
  {{- include "refinery.labels" . | nindent 4 }}
data:
  rules.toml: |
{{- .Values.rules | nindent 4 }}